### ISSUE TITLE
adjust data signed by merchant for mutual close?

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/tezos-contract#10]
The merchant's EdDSA PK is associated with a tz1 address, and a merchant may choose to use this key for purposes other than zkChannels (ie this is outside of our control and based on my understanding of Tezos, would be the expected norm).

If possible, I am inclined to add some mutual-close indicator to the tuple the merchant signs during a mutual-close, i.e. have the merchant sign the tuple `("zkChannels mutual close", cid, customer_balance, merchant_balance)` .

Thoughts @jakinyele?

**Comment by jakinyele** [comment]
Definitely reasonable to add a context string (and/or a counter) to avoid the signature being reused in a different context.

**Comment by DariusParvin** [comment]
Note that in tezos/michelson there’s a command `SELF_ADDRESS` (`sp.self_address` in smartpy) for the smart contract to reference its own KT1 address, incase we want to include that in what gets signed.

**Comment by indomitableSwan** [comment]
What do we currently have in our contract @jakinyele @DariusParvin ? Should this be transferred to zkchannels-spec?

**Comment by DariusParvin** [comment]
It's been adjusted to match what's in the spec, so I think we can close this issue.

[spec](https://github.com/boltlabs-inc/zkchannels-spec/blob/main/tezos/4-channel-closure.md#mutual-close) : (contract-id, "zkChannels mutual close", cid, customer_balance, merchant_balance) 

Smartpy:
https://github.com/boltlabs-inc/tezos-contract/blob/main/zkchannels-contract/zkchannel_smartpy_script.py#L203
