### ISSUE TITLE
Update gas/storage cost breakdown

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/tezos-contract#13]
Old numbers here -> https://github.com/boltlabs-inc/libzkchannels/blob/master/tezos-sandbox/docs/gas_cost_benchmarks.md

**Comment by DariusParvin** [comment]
Updated gas costs in
https://github.com/boltlabs-inc/libzkchannels/commit/97c4b01fccbb821e433ad5d3990ed644141b0dc5

Updated testnet tester to track and print fees in
https://github.com/boltlabs-inc/tezos-contract/commit/ec03a9bb8762c423fdfbba4724f04907e1da2df1
