### ISSUE TITLE
Make bls12_381_fr the default type for the revocation lock

### ISSUE THREAD

**Issue by DariusParvin** [boltlabs-inc/tezos-contract#16]
It may be possible to reduce the size of the contract by changing the type for rev_lock in storage from `bytes` to `bls_381_fr`.

A benefit of having it as `bytes` is that in the case of mutualClose, where rev_lock is **not** used, the contract can have a default value of `0x00`, rather than a 32 byte `00...` value, saving storage. This might be outweighed by not having to convert from `bytes` to `fr` in custClose.

edit: added 'not', as in rev_lock is not used in mutualClose.

**Comment by indomitableSwan** [comment]
@DariusParvin Why is rev_lock used in mutualClose at all?

Can you clarify your suggestion a bit? This would just mean the `bytes` to `fr` conversion would instead happen when calling the dispute entry point, right? Given that this is the spot where the revocation lock pair must be verified and checked against the revocation lock of the parent custClose, this seems like the correct place for a revocation lock to be encoded as `bytes` and then converted to `fr`.

**Comment by DariusParvin** [comment]
im sorry that was a mistake, i meant in the case of mutualClose where it is **not** used.

Yes the reason why both forms (`bytes` and `fr`) are needed in the contract is because for merchDispute where the secret is hashed with SHA3, the digest has type `bytes`, so rev_lock needs to be in `bytes`. And in custClose where the pairing check happens, rev_lock needs to be in `fr`. So there is some flexibility in which type we use when we store it in the contract after calling custClose.

**Comment by DariusParvin** [comment]
so the choice is either:
- we store rev_lock as `bytes` in the contract, and do the `bytes` -> `fr` conversion in custClose (how it is now)
- or store rev_lock as `fr` and do the `fr` -> `bytes` conversion during merchDispute

Both work, and it's possible that the second option results in a shorter contract when it's compiled, so it's something we can consider for optimizing for storage costs. The gains (if any) will probably be small though, so it's not a big priority for now.

**Comment by indomitableSwan** [comment]
@DariusParvin Either should be fine.

**Comment by marsella** [comment]
Per boltlabs-inc/libzkchannels#172, we should store the revocation lock as `fr`, convert `hash(secret)` from `bytes -> fr`, and compare the two as `fr`, rather than as `bytes`.

**Comment by indomitableSwan** [comment]
Can we move this higher up the priority queue @jakinyele @DariusParvin?

**Comment by jakinyele** [comment]
> Can we move this higher up the priority queue @jakinyele @DariusParvin?

Agreed!
