### ISSUE TITLE
benchmark optimization for merchant PS pubkeys

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/tezos-contract#28]
From Raphaël Cauderlier at NL:

A common pattern to avoid storing too much data on chain is to store it off-chain and only store a hash on chain. This would mean adding the points to the parameter of the entrypoint used to close a channel and checking that the hash of the points passed as parameter is identical to the one that is stored.

The advantages of doing so are:

- It does not require a protocol amendment, you can do it today,
- A hash takes even less space than a compressed BLS12 point,
- Hashing a point will probably be much less gas expensive than decompressing a point (because to decompress we need to compute a square root).

The only drawback is that the points must still be stored off-chain, by whoever cares about the future possibility of closing the channel. If this is a problem for you, there a trick to store it in the chain history instead of the context: https://forum.tezosagora.org/t/artcontracts-on-chain-art-via-tezos-smart-contracts/3341/2.

Related to #14

**Comment by indomitableSwan** [comment]
@jakinyele Do we have a conclusion as to feasibility of this approach?

**Comment by jakinyele** [comment]
@indomitableSwan we now have benchmarks for this optimization. Plan is to hold off on when we're done with initial zeekoe-tezos integration before merging.

**Comment by indomitableSwan** [comment]
@jakinyele Does that mean the benchmarks showed this change is a clear win? Do we have the plan to merge the change documented somewhere, ie as a conclusion on the draft PR?

**Comment by jakinyele** [comment]
@indomitableSwan yeah, the optimization does reduce origination costs by 22% and storage by 17%. There's a [wiki page](https://github.com/boltlabs-inc/tezos-contract/wiki/Benchmark-Results#optimized-contract-benchmark-comparison) for the results. Maybe it's worth adding this conclusion (if you agree) and the plan to merge as an epic under M4?
