### ISSUE TITLE
SmartPy review

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/tezos-contract#4]
An informal review of our use of SmartPy language features and possible ways to optimize contract storage and gas costs.

**Comment by DariusParvin** [comment]
Thanks for the thorough review @rumkeller! The updated version of the script is [here](https://github.com/boltlabs-inc/tezos-contract/blob/smartpy-review/zkchannels-contract/zkchannel_smartpy_script.py). To address your points:

> - If the merchant is a smart contract that refuses incoming funds, `sp.send(self.data.merchAddr, merchBal)` will result in a failing transaction. This gives the merchant a way to prevent the customer from calling the `custClose` entry point.
> - Similarly, the merchant and the customer can prevent each other from calling the `mutualClose` entry point.

Now the contract will always check that the amount is not 0 before doing a transfer, e.g.:
```
        sp.if merchBal != sp.tez(0):
            sp.send(self.data.merchAddr, merchBal)
```

> - If either the customer or the merchent calls `addFunding` several times, the transfer is accepted, but not recorded. Suggestion: `add sp.verify(self.data.custBal == 0)` and `sp.verify(self.data.merchBal == 0)`
> - If a third party calls `addFunding`, the amount remains locked in the contract forever. Suggestion: fail if sp.sender is neither the customer, nor the merchant.

Now, `addFunding` will make sure the balance is 0 before adding funds, e.g.:
```
            sp.verify(self.data.custBal == sp.tez(0))
```
I believe this solves both issues above as it prevents `addFunding` being called multiple times. It doesn't prevent a third party from funding the channel, but I don't think that's something we want to necessarily exclude for now at least. If a third party does fund the channel then things should continue as normal, as if the customer or merchant had funded it. 

> - Many of the fields in the storage (e.g. custFunding) do not change during the contract's lifetime. Using global variables or attributes (self.custFunding instead of self.data.custFunding) would lead to smaller storage and code.
Great point! We'll make this optimization when the contract is more finalized and we have a working node, as it would add some complexity to generating and verifying the smart contract. 

> - Entry points can take several parameters directly, e.g.:def custClose(self, custBal, merchBal, ...)

Removed the use of `params`.

**Comment by rumkeller** [comment]
It seems that the first (and second) issue persist.

Once the contract is OPEN, any path in the state graph that refunds the customer goes through either `custClose` or `mutualClose` calls. Both these entry points make a call `sp.send(self.data.merchAddr, merchBal)` (if `merchBal` is non-zero). A malevolent merchant could refuse any transaction that goes to `merchAddr` (by calling `FAIL`) and thus prevent the customer from making any of these calls.

This may not be a problem if it is known that both merchant and customer are implicit accounts (tz1 addresses). If this assumption is made, I'd suggest documenting it along with the contract.

**Comment by jakinyele** [comment]
@DariusParvin correct me if done already but let's also document the restriction to implicit accounts in the zkchannels-spec as well.

**Comment by DariusParvin** [comment]
Ah okay, I misunderstood the issue the at first but it makes sense now. The off-chain protocol will require that the customer and merchant are both using implicit accounts, but I will make sure it's documented (in the contract and in the document). Thanks a lot!
