### ISSUE TITLE
Migrate to SHA3-256 from SHA256

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/tezos-contract#7]
We are changing our revocation lock/secret pairs to be formed using SHA3-256 instead of SHA256.

**Comment by indomitableSwan** [comment]
Have we done this? @DariusParvin @jakinyele

**Comment by jakinyele** [comment]
Correct! I think we can close this issue now (can you confirm @DariusParvin?)

**Comment by indomitableSwan** [comment]
can we point to commit(s) @DariusParvin

**Comment by DariusParvin** [comment]
Here's the commit 

https://github.com/boltlabs-inc/tezos-contract/commit/612acc17602a348ff4929aa687d3fa2bc38273e3
